version: 2 # use CircleCI 2.0
jobs: 
  build: 

    working_directory: ~/circleci-demo-python-django
    docker: 
      - image: circleci/python:3.6.4

    steps: 
      - checkout
      - run:
          command: |
            sudo pip install -r requirements.txt
            pipenv install
      - run:
          command: |
            python -m unittest discover
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
          destination: tr1