version: 2 # use CircleCI 2.0
jobs: 
  build: 

    working_directory: ~/circleci-railway-infrastructure_test
    docker: 
      - image: circleci/python:3.8.3

    steps: 
      - checkout
      - run:
          command: |
            sudo pip install -r requirements.txt
      - run:
          command: |
            python -m unittest discover
