version: 2 # use CircleCI 2.0
jobs:
  build:

    working_directory: ~/circleci-railway-infrastructure_test
    docker:
      - image: circleci/python:3.8.3

    steps:
      - checkout
      - run: Install requirements
          command: |
            sudo pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            python -m unittest discover -s tests

      - run:
          name: Run pylint
          command: |
            pip install pylint
            pylint src
